spring.application.name=shopping-api
server.port=8087

spring.data.mongodb.uri=mongodb+srv://eliezerrocha_db_user:<db_password>@cluster0.ubxtofj.mongodb.net/shopping_db?appName=Cluster0
spring.data.mongodb.database=shopping_db

