server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogo-service
              uri: ${CATALOGO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/catalogo/**
              filters:
                - StripPrefix=1

            - id: cliente-service
              uri: ${CLIENTE_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/clientes/**

            - id: pedido-service
              uri: ${PEDIDO_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/pedidos/**
